// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsAppPlatform.Infrastructure.Persistence;

#nullable disable

namespace WhatsAppPlatform.Infrastructure.WhatsAppAccounts.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261006154412_TreatExternalIdentifiersAsOpaque")]
    partial class TreatExternalIdentifiersAsOpaque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppPlatform.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending();

                    b.ToTable("organizations", "organizations", t =>
                        {
                            t.HasCheckConstraint("ck_organizations_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_organizations_status", "status IN ('Active', 'Suspended')");
                        });
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.EmbeddedSignupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "StartedAt");

                    b.ToTable("embedded_signup_sessions", "whatsapp", t =>
                        {
                            t.HasCheckConstraint("ck_signup_completion", "(status = 'Completed' AND completed_at IS NOT NULL AND completed_at >= started_at AND completed_at < expires_at) OR (status <> 'Completed' AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_signup_expiry", "expires_at > started_at");

                            t.HasCheckConstraint("ck_signup_status", "status IN ('Pending', 'Completed', 'Failed', 'Expired')");
                        });
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.MessagingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalMessagingAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_messaging_account_id");

                    b.Property<Guid>("WhatsAppAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("whatsapp_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalMessagingAccountId")
                        .IsUnique();

                    b.HasIndex("WhatsAppAccountId")
                        .IsUnique();

                    b.ToTable("messaging_accounts", "whatsapp", t =>
                        {
                            t.HasCheckConstraint("ck_messaging_external_id", "char_length(external_messaging_account_id) BETWEEN 1 AND 100 AND btrim(external_messaging_account_id, U&'\\0020\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') <> '' AND external_messaging_account_id !~ U&'[\\0001-\\001F\\007F-\\009F]'");
                        });
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_phone_number");

                    b.Property<string>("ExternalPhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_phone_number_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VerifiedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verified_name");

                    b.Property<Guid>("WhatsAppAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("whatsapp_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPhoneNumberId")
                        .IsUnique();

                    b.HasIndex("WhatsAppAccountId");

                    b.ToTable("phone_numbers", "whatsapp", t =>
                        {
                            t.HasCheckConstraint("ck_phone_display", "length(btrim(display_phone_number)) > 0");

                            t.HasCheckConstraint("ck_phone_external_id", "char_length(external_phone_number_id) BETWEEN 1 AND 100 AND btrim(external_phone_number_id, U&'\\0020\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') <> '' AND external_phone_number_id !~ U&'[\\0001-\\001F\\007F-\\009F]'");

                            t.HasCheckConstraint("ck_phone_status", "status = 'Registered'");
                        });
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.WhatsAppAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalWhatsAppAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_whatsapp_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SignupSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("signup_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalWhatsAppAccountId")
                        .IsUnique();

                    b.HasIndex("SignupSessionId")
                        .IsUnique();

                    b.HasIndex("SignupSessionId", "OrganizationId");

                    b.HasIndex("OrganizationId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("accounts", "whatsapp", t =>
                        {
                            t.HasCheckConstraint("ck_account_connected", "status <> 'Connected' OR (connected_at IS NOT NULL AND connected_at >= created_at)");

                            t.HasCheckConstraint("ck_account_external_id", "char_length(external_whatsapp_account_id) BETWEEN 1 AND 100 AND btrim(external_whatsapp_account_id, U&'\\0020\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000') <> '' AND external_whatsapp_account_id !~ U&'[\\0001-\\001F\\007F-\\009F]'");

                            t.HasCheckConstraint("ck_account_name", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_account_status", "status IN ('Pending', 'Connected', 'Suspended', 'Disconnected')");
                        });
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.EmbeddedSignupSession", b =>
                {
                    b.HasOne("WhatsAppPlatform.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.MessagingAccount", b =>
                {
                    b.HasOne("WhatsAppPlatform.Domain.WhatsAppAccounts.WhatsAppAccount", null)
                        .WithMany()
                        .HasForeignKey("WhatsAppAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.PhoneNumber", b =>
                {
                    b.HasOne("WhatsAppPlatform.Domain.WhatsAppAccounts.WhatsAppAccount", null)
                        .WithMany()
                        .HasForeignKey("WhatsAppAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WhatsAppPlatform.Domain.WhatsAppAccounts.WhatsAppAccount", b =>
                {
                    b.HasOne("WhatsAppPlatform.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatsAppPlatform.Domain.WhatsAppAccounts.EmbeddedSignupSession", null)
                        .WithMany()
                        .HasForeignKey("SignupSessionId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
